# Generated by Django 3.2.7 on 2021-10-03 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='image_url',
        ),
        migrations.AddField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polloption',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
