# Generated by Django 3.2.5 on 2021-09-03 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollvote",
            name="user",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="auth.user"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="PollStatus",),
    ]
