# Generated by Django 3.2.5 on 2021-09-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_auto_20210903_1656"),
    ]

    operations = [
        migrations.RemoveField(model_name="pollvote", name="school",),
        migrations.RemoveField(model_name="pollvote", name="year",),
        migrations.AddField(
            model_name="pollvote",
            name="poll",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="portal.poll"
            ),
            preserve_default=False,
        ),
    ]
