# Generated by Django 3.2.7 on 2021-10-04 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="image_url",
        ),
        migrations.AddField(
            model_name="poll",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="polloption",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="targetpopulation",
            name="kind",
            field=models.CharField(
                choices=[("SCHOOL", "School"), ("YEAR", "Year"), ("MAJOR", "Major")],
                default="SCHOOL",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="target_populations",
            field=models.ManyToManyField(blank=True, to="portal.TargetPopulation"),
        ),
    ]
