# Generated by Django 3.2.7 on 2021-10-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_auto_20211003_2225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetpopulation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SCHOOL", "School"),
                    ("YEAR", "Year"),
                    ("MAJOR", "Major"),
                    ("DEGREE", "Degree"),
                ],
                default="SCHOOL",
                max_length=10,
            ),
        ),
    ]
