# Generated by Django 3.2.7 on 2021-10-22 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0003_alter_targetpopulation_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("post_url", models.URLField(null=True)),
                ("image_url", models.URLField(null=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("expire_date", models.DateTimeField()),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("admin_comment", models.CharField(blank=True, max_length=255, null=True)),
                ("user_comment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "target_populations",
                    models.ManyToManyField(blank=True, to="portal.TargetPopulation"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        )
    ]
