# Generated by Django 4.0.1 on 2022-01-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("portal", "0008_alter_post_image_url")]

    operations = [migrations.RenameField(model_name="post", old_name="image_url", new_name="image")]
