# Generated by Django 4.0.1 on 2022-02-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("portal", "0009_rename_image_url_post_image")]

    operations = [migrations.RemoveField(model_name="post", name="image")]
