# Generated by Django 4.0.1 on 2022-02-02 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0011_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
