# Generated by Django 3.1.5 on 2021-02-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaundrySnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("room", models.IntegerField()),
                ("date", models.DateTimeField(auto_now=True)),
                ("available_washers", models.IntegerField()),
                ("available_dryers", models.IntegerField()),
                ("total_washers", models.IntegerField()),
                ("total_dryers", models.IntegerField()),
            ],
        ),
    ]
