# Generated by Django 3.1.5 on 2021-02-07 17:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaundryRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hall_id", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name="LaundrySnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("room", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("available_washers", models.IntegerField()),
                ("available_dryers", models.IntegerField()),
                ("total_washers", models.IntegerField()),
                ("total_dryers", models.IntegerField()),
            ],
        ),
    ]
