# Generated by Django 3.1.7 on 2021-03-17 03:12

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("laundry", "0001_initial"), ("laundry", "0002_auto_20210316_2312")]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaundryRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hall_id", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("total_washers", models.IntegerField(default=0)),
                ("total_dryers", models.IntegerField(default=0)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name="LaundrySnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("available_washers", models.IntegerField()),
                ("available_dryers", models.IntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laundry.laundryroom",
                    ),
                ),
            ],
        ),
    ]
