# Generated by Django 3.1.5 on 2021-02-05 23:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('uiud', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.AlterField(
            model_name='laundrysnapshot',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
