# Generated by Django 3.1.5 on 2021-02-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="laundrysnapshot", old_name="room", new_name="hall_id",),
    ]
