# Generated by Django 3.1.5 on 2021-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='location',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
