repos:
  - repo: https://github.com/pennlabs/pre-commit-hooks
    rev: v1.1-mobile-backend
    hooks:
      - id: black
        args: [-l100]
      - id: isort
        args: []
      - id: flake8
        args: [--config, backend/setup.cfg]
      - id: detect-private-key