repos:
  - repo: https://github.com/pennlabs/pre-commit-hooks
    rev: v1.1-mobile-backend
    hooks:
      - id: black
        args: [-l100]
      - id: isort
        args: []
      - id: flake8
        args: [--config, backend/setup.cfg]
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Use the latest version
    hooks:
      - id: mypy
        additional_dependencies: [
          'types-requests',
          'types-python-dateutil',
          'django-stubs',
          'djangorestframework-stubs',
        ]
        args: [
          --strict,
          --ignore-missing-imports,
          --disallow-untyped-defs,
          --disallow-incomplete-defs,
          --check-untyped-defs,
          --disallow-untyped-decorators,
          --no-implicit-optional,
          --warn-redundant-casts,
          --warn-unused-ignores,
          --warn-return-any,
          --no-implicit-reexport,
        ]