repos:
  - repo: https://github.com/pennlabs/pre-commit-hooks
    rev: a91c550e051920dcb36e123fe8e2edac66ebf937
    hooks:
      - id: black
        args: [-l100]
      - id: isort
        args: []
      - id: flake8
        args: [--config, backend/setup.cfg]
      - id: detect-private-key