repos:
  - repo: https://github.com/pennlabs/pre-commit-hooks
    rev: stable
    hooks:
        - id: isort
        - id: flake8
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
        - id: black
