# Generated by Django 3.1.7 on 2021-06-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsr_booking", "0003_gsr_gsrbooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gsrbooking",
            name="name",
            field=models.CharField(default="name", max_length=255),
            preserve_default=False,
        ),
    ]
