# Generated by Django 3.1.7 on 2021-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsr_booking", "0004_auto_20210628_1804"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gsrbooking",
            name="booking_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
