# Generated by Django 3.1.7 on 2021-06-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsr_booking", "0005_auto_20210629_1653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gsrbooking",
            name="booking_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
