# Generated by Django 3.2.5 on 2021-09-02 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gsr_booking', '0007_auto_20210718_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gsrbooking',
            old_name='room',
            new_name='gsr',
        ),
        migrations.RenameField(
            model_name='gsrbooking',
            old_name='name',
            new_name='room_name',
        ),
        migrations.RemoveField(
            model_name='gsr',
            name='rid',
        ),
        migrations.RemoveField(
            model_name='gsrbooking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='gsrbooking',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='gsrbooking',
            name='size',
        ),
        migrations.AddField(
            model_name='gsrbooking',
            name='room_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gsrbooking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gsr',
            name='gid',
            field=models.IntegerField(null=True),
        ),
    ]
