# Generated by Django 3.1.7 on 2021-03-17 03:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("dining", "0001_initial"),
        ("dining", "0002_diningpreference"),
        ("dining", "0003_diningtransaction"),
        ("dining", "0004_remove_diningtransaction_balance"),
        ("dining", "0005_auto_20210314_0028"),
        ("dining", "0006_diningtransaction_balance"),
        ("dining", "0007_diningbalance"),
        ("dining", "0008_auto_20210314_0120"),
        ("dining", "0009_auto_20210314_1732"),
        ("dining", "0010_auto_20210314_1802"),
        ("dining", "0011_auto_20210316_2131"),
        ("dining", "0012_auto_20210316_2138"),
        ("dining", "0013_auto_20210316_2139"),
        ("dining", "0014_auto_20210316_2139"),
    ]

    initial = True

    dependencies = [
        ("user", "0004_remove_profile_dining_preferences"),
        ("user", "0005_profile_dining_balance"),
        ("user", "0006_remove_profile_dining_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("venue_id", models.IntegerField()),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="DiningTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateTimeField()),
                ("description", models.TextField()),
                ("amount", models.FloatField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
                ("balance", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DiningBalance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("dining_dollars", models.FloatField()),
                ("swipes", models.IntegerField()),
                ("guest_swipes", models.IntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiningPreference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dining.venue"
                    ),
                ),
            ],
        ),
    ]
