# Generated by Django 3.1.7 on 2021-03-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("venue_id", models.IntegerField()),
                ("image_url", models.URLField()),
            ],
        ),
    ]
