# Generated by Django 3.1.7 on 2021-03-14 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_profile_dining_balance"),
        ("dining", "0002_diningpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiningTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("amount", models.FloatField()),
                ("balance", models.FloatField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
        ),
    ]
