# Generated by Django 3.1.7 on 2021-03-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0003_diningtransaction"),
    ]

    operations = [
        migrations.RemoveField(model_name="diningtransaction", name="balance",),
    ]
