# Generated by Django 3.1.7 on 2021-03-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0004_remove_diningtransaction_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diningtransaction", name="date", field=models.DateTimeField(),
        ),
    ]
