# Generated by Django 3.1.7 on 2021-03-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0005_auto_20210314_0028"),
    ]

    operations = [
        migrations.AddField(
            model_name="diningtransaction", name="balance", field=models.FloatField(default=0),
        ),
    ]
