# Generated by Django 3.1.7 on 2021-03-14 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_profile_dining_balance"),
        ("dining", "0006_diningtransaction_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiningBalance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("dining_dollars", models.FloatField()),
                ("swipes", models.IntegerField()),
                ("guest_swipes", models.IntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
        ),
    ]
