# Generated by Django 3.1.7 on 2021-03-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0007_diningbalance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diningbalance", old_name="dining_dollars", new_name="dollars",
        ),
    ]
