# Generated by Django 3.1.7 on 2021-03-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0008_auto_20210314_0120"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diningbalance", old_name="dollars", new_name="dining_dollars",
        ),
    ]
