# Generated by Django 3.1.7 on 2021-03-14 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0009_auto_20210314_1732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diningbalance",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
