# Generated by Django 3.1.7 on 2021-03-17 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0011_auto_20210316_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diningpreference',
            name='venue',
        ),
        migrations.AddField(
            model_name='diningpreference',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dining.venue'),
        ),
    ]
