# Generated by Django 3.1.7 on 2021-03-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0013_auto_20210316_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningpreference',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dining.venue'),
        ),
    ]
