# Generated by Django 5.0.2 on 2026-02-27 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("board", models.JSONField()),
                ("possible_words", models.JSONField()),
                ("seed", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score", models.PositiveIntegerField(db_index=True)),
                ("words_found", models.PositiveIntegerField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_hunt_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "words_found", "submitted_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="leaderboardentry",
            constraint=models.UniqueConstraint(
                fields=("game", "user"), name="unique_entry_per_user_per_game"
            ),
        ),
    ]
