# Generated by Django 5.0.2 on 2026-03-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="freqs",
            field=models.JSONField(default=dict),
        ),
    ]
