# Generated by Django 5.0.2 on 2026-03-30 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_freqs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaderboardentry",
            options={"ordering": ["-score"]},
        ),
        migrations.RenameField(
            model_name="game",
            old_name="freqs",
            new_name="word_length_freq",
        ),
        migrations.RenameField(
            model_name="leaderboardentry",
            old_name="words_found",
            new_name="num_words_found",
        ),
    ]
