# Generated by Django 5.0.2 on 2026-09-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_leaderboardentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="show_name",
            field=models.BooleanField(default=False),
        ),
    ]
