# Generated by Django 5.0.2 on 2026-09-20 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_show_name_to_game_user(apps, schema_editor):
    LeaderboardEntry = apps.get_model("games", "LeaderboardEntry")
    GameUser = apps.get_model("games", "GameUser")
    prefs = {}
    for user_id, show_name in LeaderboardEntry.objects.values_list("user_id", "show_name"):
        prefs[user_id] = prefs.get(user_id, False) or show_name
    GameUser.objects.bulk_create(
        [GameUser(user_id=user_id, show_name=show_name) for user_id, show_name in prefs.items()]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_leaderboardentry_show_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("show_name", models.BooleanField(default=False)),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gameuser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameUserTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("value", models.CharField(max_length=255)),
                (
                    "game_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="games.gameuser",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="gameusertag",
            index=models.Index(fields=["kind", "value"], name="games_gameu_kind_15bc38_idx"),
        ),
        migrations.RunPython(copy_show_name_to_game_user, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="leaderboardentry",
            name="show_name",
        ),
    ]
