# Generated by Django 5.0.2 on 2026-09-20 19:36

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_show_name_to_game_user(apps, schema_editor):
    LeaderboardEntry = apps.get_model("games", "LeaderboardEntry")
    table = apps.get_model("games", "GameUser")._meta.db_table
    prefs = {}
    for user_id, show_name in LeaderboardEntry.objects.values_list("user_id", "show_name"):
        prefs[user_id] = prefs.get(user_id, False) or show_name
    if not prefs:
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.executemany(
            f"INSERT INTO {table} (user_ptr_id, show_name) VALUES (%s, %s)",
            list(prefs.items()),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("games", "0004_leaderboardentry_show_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("show_name", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RunPython(copy_show_name_to_game_user, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="leaderboardentry",
            name="show_name",
        ),
    ]
