# Generated by Django 5.0.2 on 2026-09-20 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_show_name_to_anonymized(apps, schema_editor):
    LeaderboardEntry = apps.get_model("games", "LeaderboardEntry")
    GameUser = apps.get_model("games", "GameUser")
    prefs = {}
    for user_id, show_name in LeaderboardEntry.objects.values_list("user_id", "show_name"):
        prefs[user_id] = prefs.get(user_id, False) or show_name
    GameUser.objects.bulk_create(
        [
            GameUser(user_id=user_id, anonymized=not show_name)
            for user_id, show_name in prefs.items()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_leaderboardentry_show_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anonymized", models.BooleanField(default=True)),
                ("school", models.CharField(blank=True, max_length=255)),
                ("major", models.CharField(blank=True, max_length=255)),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gameuser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(copy_show_name_to_anonymized, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="leaderboardentry",
            name="show_name",
        ),
    ]
