# Generated by Django 5.0.2 on 2026-09-20 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_gameuser_remove_leaderboardentry_show_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameuser",
            name="graduation_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GameUserTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("value", models.CharField(max_length=255)),
                (
                    "game_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="games.gameuser",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["kind", "value"], name="games_gameu_kind_15bc38_idx")
                ],
            },
        ),
    ]
