# Generated by Django 5.0.2 on 2024-11-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0002_auto_20210321_1105"),
    ]

    operations = [
        migrations.RenameField(
            model_name="laundryroom",
            old_name="hall_id",
            new_name="room_id",
        ),
        migrations.RemoveField(
            model_name="laundryroom",
            name="uuid",
        ),
        migrations.AddField(
            model_name="laundryroom",
            name="location_id",
            field=models.IntegerField(default=0),
        ),
    ]
