# Generated by Django 5.0.2 on 2024-11-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0003_rename_hall_id_laundryroom_room_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laundryroom",
            name="room_id",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
