# Generated by Django 5.0.2 on 2024-11-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0004_alter_laundryroom_room_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laundryroom",
            name="new",
        ),
    ]
