pretty_names = {
	'Houston HM Grill': 'Houston HM Grill',
	'Joes Cafe Mobile': "Joe's Cafe",
	'Ginger Mobile': 'Houston Ginger',
	'Houston Bento': 'Houston Bento',
	'Starbucks2Sequoia': 'Starbucks Commons',
	'0113HillExpress - Charge': 'Hill Dining',
	'1146frontera - Charge Return': 'Frontera',
	'Pret2': 'Pret',
	'Pret3': 'Pret',
	'Pret1': 'Pret',
	'Pret6': 'Pret',
	'Pret7': 'Pret',
	'Pret4': 'Pret',
	'Pret5': 'Pret',
	'Houston Ivy Leaf': 'Houston Ivy Leaf',
	'Pret8': 'Pret',
	'Starbucks Mobile': 'Starbucks Commons',
	'0144Accenture - Charge Return': 'Accenture Cafe',
	'0147MarksCafe - Charge': "Mark's Cafe",
	'Pert9': 'Pret',
	'Houston Ginger': 'Houston Ginger',
	'U Penn Canteen Vending API': 'Van Pelt Shop',
	'RHS-SFR-D9JM1G2': 'Dining',
	'0154Starbucks - Charge': 'Starbucks Commons',
	'0888JoesCafe - Charge': "Joe's Cafe",
	'AccentureSequoia': 'Accenture Cafe',
	'0100HoustonMarket - Charge Return': 'Houston Hall',
	'PNC-BOK-23TYZV2': 'Dining',
	'Houston Kiosk2': 'Houston Kiosk',
	'0121KingsCourtEnglishHse - Charge': "King's Court English House",
	'1920Res1Sequoia': '1920 Commons',
	'0143GourmetGrocer - Charge Return': 'Gourmet Grocer',
	'Houston Pi2': 'Houston Pi',
	'Houston Street Cart': 'Houston Street Cart',
	'1920Res2Sequoia': '1920 Commons',
	'Bento Mobile': 'Houston Bento',
	'KosherPad': 'Kosher Dining',
	'Houston Pi1': 'Houston Pi',
	'0142ResidentialDining - Charge': 'Residential Dining',
	'Accenture Mobile': 'Accenture Cafe',
	'0143GourmetGrocer - Charge': 'Gourmet Grocer',
	'McCellandCafeSequoia': 'McClelland',
	'JoesCafe2Sequoia': "Joe's Cafe",
	'0154Starbucks - Charge Return': 'Starbucks Commons',
	'0100HoustonMarket - Charge': 'Houston Market',
	'0111HilResidentialDining - Charge': 'Hill Dining',
	'0146CafeAtMcClelland - Charge': 'McClelland',
	'34th Street Mobile': 'Houston 34th St Carvery',
	'mealplansales': 'Meal Plan',
	'Houston 34th St Carvery': 'Houston 34th St Carvery',
	'Market Cafe Mobile': 'Market Cafe',
	'Joes1Sequoia': "Joe's Cafe",
	'GormetGrocerSequoia': 'Gourmet Grocer',
	'Hill2RP2Sequoia': 'Hill Dining',
	'Farmers Market - Charge': "Farmer's Market",
	'Penn Pi Mobile': 'Houston Pi',
	'0156Pret - Charge Return': 'Pret',
	'Canteen Vending API - Charge': 'Van Pelt Shop',
	'Ivy Leaf Mobile': 'Houston Ivy Leaf',
	'0146CafeAtMcClelland - Charge Return': 'McClelland',
	'NCHResidential': 'Lauder Residential',
	'Houston Cafe2': 'Houston Cafe',
	'Meal Plan Imports 7014 - Payment': 'Meal Plan',
	'Houston Cafe1': 'Houston Cafe',
	'Houston Kiosk3': 'Houston Kiosk',
	'Meal Plan Imports 7014 - Void Payment': 'Meal Plan',
	'Houston Kiosk1': 'Houston Kiosk',
	'Houston Kiosk7': 'Houston Kiosk',
	'Houston Kiosk6': 'Houston Kiosk',
	'Houston Kiosk5': 'Houston Kiosk',
	'Houston Kiosk4': 'Houston Kiosk',
	'Houston Kiosk8': 'Houston Kiosk',
	'meal_plan_sales - Payment': 'Your Meal Plan Deduction',
	'FarmMarket2': "Farmer's Market",
	'FarmMarket1': "Farmer's Market",
	'NCH Retail2': 'NCH Retail',
	'1146frontera - Charge': 'Frontera',
	'0147MarksCafe - Charge Return': "Mark's Cafe",
	'PNC-NSO2': '',
	'BSDBBAPPRW02': 'Dining',
	'HM Grill Mobile': 'HM Grill',
	'meal_plan_sales - Void Payment': 'Meal Plan',
	'0111HilResidentialDining - Charge Return': 'Hill Dining',
	'1145FalkKosher - Charge': 'Falk Dining Cafe',
	'0156Pret - Charge': 'Pret',
	'0888JoesCafe - Charge Return': "Joe's Cafe",
	'meal_plan_sales - Charge': 'Meal Plan Deduction',
	'1145FalkKosher - Charge Return': 'Kosher Dining',
	'NCH Retal1': 'Lauder Retail',
	'0144Accenture - Charge': 'Accenture Cafe',
	'Kosher Shabbat': 'Kosher Dining',
	'Hill1RP2Sequoia': 'Hill Dining'
}

def map_to_pretty(description):
	if description in pretty_names:
		return pretty_names[description]
	else:
		description = ''.join([i for i in description if not i.isdigit()])
		description = description.split["-"][0]
		description.replace("_", " ")
		return description