[
    {
        "LocationId": 10183,
        "TotalCapacity": 1000,
        "LocationName": "Sport Club Practices",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-30T19:15:09.71",
        "LastCount": 35,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 2106,
        "FacilityName": "Competitive Sports Staff",
        "IsClosed": false
    },
    {
        "LocationId": 9608,
        "TotalCapacity": 50,
        "LocationName": "Climbing Wall",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-24T15:13:10.543",
        "LastCount": 0,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": true
    },
    {
        "LocationId": 10222,
        "TotalCapacity": 25,
        "LocationName": "Rec Lounge",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-31T07:39:04.817",
        "LastCount": 0,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": false
    },
    {
        "LocationId": 9609,
        "TotalCapacity": 65,
        "LocationName": "1st Floor Fitness",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-31T07:39:05.553",
        "LastCount": 12,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": false
    },
    {
        "LocationId": 9606,
        "TotalCapacity": 10,
        "LocationName": "Court 1",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-31T07:39:06.37",
        "LastCount": 1,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": false
    },
    {
        "LocationId": 9889,
        "TotalCapacity": 10,
        "LocationName": "Court 2",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-31T07:39:06.99",
        "LastCount": 0,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": false
    },
    {
        "LocationId": 9890,
        "TotalCapacity": 10,
        "LocationName": "Court 3",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-31T07:39:07.613",
        "LastCount": 10,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": false
    },
    {
        "LocationId": 9607,
        "TotalCapacity": 100,
        "LocationName": "Multipurpose Room",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-31T07:39:08.367",
        "LastCount": 14,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": false
    },
    {
        "LocationId": 9610,
        "TotalCapacity": 178,
        "LocationName": "2nd Floor Weight Room",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-31T07:39:08.99",
        "LastCount": 20,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": false
    },
    {
        "LocationId": 9611,
        "TotalCapacity": 68,
        "LocationName": "3rd Floor Fitness Room",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-31T07:39:09.693",
        "LastCount": 6,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": false
    },
    {
        "LocationId": 9616,
        "TotalCapacity": 56,
        "LocationName": "4th Floor Fitness Room",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-31T07:39:10.287",
        "LastCount": 3,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": false
    },
    {
        "LocationId": 9617,
        "TotalCapacity": 100,
        "LocationName": "Studio 409",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-31T07:39:11.083",
        "LastCount": 11,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": false
    },
    {
        "LocationId": 11079,
        "TotalCapacity": 50,
        "LocationName": "Sheerr Pool",
        "CountOfParticipants": 0,
        "PercetageCapacity": 0,
        "LastUpdatedDateAndTime": "2025-10-31T07:39:11.71",
        "LastCount": 6,
        "MinColor": "#ffc90e",
        "MidColor": null,
        "MaxColor": "#ed1c24",
        "MinCapacityRange": 60,
        "MaxCapacityRange": 90,
        "CountCapacityColorEnabled": true,
        "FacilityId": 1961,
        "FacilityName": "Pottruck Health & Fitness Center",
        "IsClosed": false
    }
]