# Generated by Django 3.1.7 on 2021-03-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0001_initial"),
        ("user", "0003_profile_dining_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dining_preferences",
            field=models.ManyToManyField(blank=True, to="dining.Venue"),
        ),
    ]
