deploy_version: 0.1.20
image_tag: latest

applications:
  - name: django
    image: pennlabs/penn-mobile-backend-staging
    secret: penn-mobile
    replicas: 1
    ingress:
      hosts:
        - host: staging-portal.pennmobile.org
          paths: ["/api", "/assets"]
    extraEnv:
      - name: DOMAINS
        value: staging-portal.pennmobile.org
      - name: DJANGO_SETTINGS_MODULE
        value: pennmobile.settings.production
      - name: DATABASE_URL
        value: postgres://penn-mobile:gary@penn-mobile-test-postgres:5432/penn-mobile
  - name: react
    image: pennlabs/penn-mobile-frontend-staging
    ingress:
      hosts:
        - host: staging-portal.pennmobile.org
          paths: ["/"]
    extraEnv:
      - name: PORT
        value: 80
      - name: DOMAIN
        value: staging-portal.pennmobile.org
  - name: postgres
    image: postgres:12
    svc_type: NodePort
    port: 5432
    extraEnv:
      - name: POSTGRES_DB
        value: penn-mobile
      - name: POSTGRES_PASSWORD
        value: gary
      - name: POSTGRES_USER
        value: penn-mobile