# Generated by Django 3.1.7 on 2021-03-23 21:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_profile_laundry_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("venue_id", models.IntegerField(primary_key=True, serialize=False)),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="DiningTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateTimeField()),
                ("description", models.TextField()),
                ("amount", models.FloatField()),
                ("balance", models.FloatField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiningBalance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("dining_dollars", models.FloatField()),
                ("swipes", models.IntegerField()),
                ("guest_swipes", models.IntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
        ),
    ]
