# Generated by Django 4.0.3 on 2022-10-06 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningItem',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiningStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(to='dining.diningitem')),
            ],
        ),
        migrations.CreateModel(
            name='DiningMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('service', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('BRUNCH', 'Brunch'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=30)),
                ('stations', models.ManyToManyField(to='dining.diningstation')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dining.venue')),
            ],
        ),
    ]
