# Generated by Django 4.0.3 on 2022-10-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0003_venue_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diningtransaction",
            name="profile",
        ),
        migrations.AlterField(
            model_name="diningitem",
            name="description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="diningitem",
            name="ingredients",
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name="DiningBalance",
        ),
        migrations.DeleteModel(
            name="DiningTransaction",
        ),
    ]
