# Generated by Django 5.0.2 on 2024-04-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dining", "0004_remove_diningtransaction_profile_and_more")]

    operations = [
        migrations.AddField(
            model_name="diningitem",
            name="allergens",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diningitem",
            name="nutrition_info",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diningstation",
            name="menu",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="dining.diningmenu"
            ),
            preserve_default=False,
        ),
    ]
