# Generated by Django 5.0.2 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0006_remove_diningmenu_stations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diningitem",
            name="allergens",
        ),
        migrations.AddField(
            model_name="diningitem",
            name="ask_us",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="egg",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="fish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="jain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="kosher",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="milk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="peanut",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="sesame",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="soy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="tree_nut",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="vegan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="vegetarian",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningitem",
            name="wheat_gluten",
            field=models.BooleanField(default=False),
        ),
    ]
