# Generated by Django 5.0.2 on 2024-10-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="used",
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.FloatField(),
        ),
    ]
