# Generated by Django 5.0.2 on 2024-11-02 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_remove_item_used_alter_item_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="market.category"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_listed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(blank=True, to="market.tag"),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="item",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="market.item"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="item",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="market.item"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
