# Generated by Django 5.0.2 on 2024-11-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_item_category_alter_item_seller_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemimage",
            old_name="image",
            new_name="images",
        ),
    ]
