# Generated by Django 5.0.2 on 2024-11-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_rename_image_itemimage_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemimage",
            old_name="images",
            new_name="image",
        ),
    ]
