# Generated by Django 5.0.2 on 2024-11-08 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_rename_images_itemimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="images", to="market.item"
            ),
        ),
    ]
