# Generated by Django 5.0.2 on 2025-01-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_alter_itemimage_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sublet",
            name="baths",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="sublet",
            name="beds",
            field=models.FloatField(),
        ),
    ]
