# Generated by Django 5.0.2 on 2025-01-23 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_alter_sublet_baths_alter_sublet_beds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="offer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
