# Generated by Django 5.0.2 on 2025-02-16 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_rename_created_date_offer_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["title"], name="market_item_title_c9d008_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["price"], name="market_item_price_844140_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["created_at"], name="market_item_created_7d7f6f_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["expires_at"], name="market_item_expires_2a5f68_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["negotiable"], name="market_item_negotia_5dc7ce_idx"),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["user"], name="market_offe_user_id_48d792_idx"),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["item"], name="market_offe_item_id_8153c3_idx"),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["created_at"], name="market_offe_created_e6ee0e_idx"),
        ),
        migrations.AddIndex(
            model_name="sublet",
            index=models.Index(fields=["start_date"], name="market_subl_start_d_255959_idx"),
        ),
        migrations.AddIndex(
            model_name="sublet",
            index=models.Index(fields=["end_date"], name="market_subl_end_dat_673330_idx"),
        ),
        migrations.AddIndex(
            model_name="sublet",
            index=models.Index(fields=["beds"], name="market_subl_beds_b389b9_idx"),
        ),
        migrations.AddIndex(
            model_name="sublet",
            index=models.Index(fields=["baths"], name="market_subl_baths_b4bb84_idx"),
        ),
    ]
