# Generated by Django 5.0.2 on 2024-11-10 16:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStatKey',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualStatKey',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalStatPageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_name', models.CharField(max_length=50)),
                ('global_stat_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wrapped.globalstatkey')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualStatPageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_name', models.CharField(max_length=50)),
                ('individual_stat_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wrapped.individualstatkey')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('template_path', models.CharField(max_length=50)),
                ('duration', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('global_stats', models.ManyToManyField(blank=True, through='wrapped.GlobalStatPageField', to='wrapped.globalstatkey')),
                ('individual_stats', models.ManyToManyField(blank=True, through='wrapped.IndividualStatPageField', to='wrapped.individualstatkey')),
            ],
        ),
        migrations.AddField(
            model_name='individualstatpagefield',
            name='Page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.page'),
        ),
        migrations.AddField(
            model_name='globalstatpagefield',
            name='Page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.page'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('pages', models.ManyToManyField(blank=True, to='wrapped.page')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.individualstatkey')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.semester')),
            ],
            options={
                'unique_together': {('key', 'semester', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GlobalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.globalstatkey')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.semester')),
            ],
            options={
                'unique_together': {('key', 'semester')},
            },
        ),
    ]
