# Generated by Django 5.0.2 on 2024-10-11 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(max_length=50)),
                ('template', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_key', models.CharField(max_length=50)),
                ('stat_value', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=5)),
            ],
            options={
                'unique_together': {('stat_key', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.template')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stat_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.userstatkey')),
            ],
            options={
                'unique_together': {('stat_key', 'semester', 'user')},
            },
        ),
    ]
