# Generated by Django 5.0.2 on 2025-10-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(fields=("name",), name="page_name_unique"),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(fields=("semester",), name="semester_unique"),
        ),
    ]
