# Generated by Django 5.0.2 on 2024-11-10 17:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="globalstatpagefield",
            old_name="Page",
            new_name="page",
        ),
        migrations.RenameField(
            model_name="individualstatpagefield",
            old_name="Page",
            new_name="page",
        ),
        migrations.AlterField(
            model_name="page",
            name="duration",
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
