# Generated by Django 5.0.2 on 2024-10-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='template',
            name='background',
        ),
        migrations.RemoveField(
            model_name='template',
            name='template',
        ),
        migrations.AddField(
            model_name='page',
            name='GlobalStat',
            field=models.ManyToManyField(to='wrapped.globalstat'),
        ),
        migrations.AddField(
            model_name='page',
            name='IndividualStat',
            field=models.ManyToManyField(to='wrapped.individualstat'),
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='wrapped.template'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='num_fields',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='template_path',
            field=models.CharField(default='hhell', max_length=50),
            preserve_default=False,
        ),
    ]
