# Generated by Django 5.0.2 on 2024-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0002_rename_page_globalstatpagefield_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="template_path",
            field=models.CharField(max_length=200),
        ),
    ]
