# Generated by Django 5.0.2 on 2024-10-18 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0002_remove_page_temp_remove_template_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='template',
        ),
        migrations.RemoveField(
            model_name='page',
            name='GlobalStat',
        ),
        migrations.RemoveField(
            model_name='page',
            name='IndividualStat',
        ),
        migrations.AddField(
            model_name='page',
            name='template_path',
            field=models.CharField(default='nothing', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StatLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_name', models.CharField(max_length=50)),
                ('GlobalStatKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.globalstat')),
                ('IndividualStatKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.userstatkey')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='stat_locations',
            field=models.ManyToManyField(blank=True, to='wrapped.statlocation'),
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
