# Generated by Django 5.0.2 on 2024-10-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0003_remove_page_template_remove_page_globalstat_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='statlocation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('GlobalStatKey', False), ('IndividualStatKey', True)), models.Q(('GlobalStatKey', True), ('IndividualStatKey', False)), _connector='OR'), name='one_foreign_key_must_be_null'),
        ),
    ]
