# Generated by Django 5.0.2 on 2025-04-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0003_alter_page_template_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
