# Generated by Django 5.0.2 on 2025-05-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0004_page_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="semester",
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
