# Generated by Django 5.0.2 on 2024-10-18 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0004_statlocation_one_foreign_key_must_be_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statlocation',
            name='GlobalStatKey',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrapped.globalstat'),
        ),
        migrations.AlterField(
            model_name='statlocation',
            name='IndividualStatKey',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrapped.userstatkey'),
        ),
    ]
