# Generated by Django 5.0.2 on 2025-10-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0005_alter_semester_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                condition=models.Q(("current", True)),
                fields=("current",),
                name="unique_current_semester",
            ),
        ),
    ]
