# Generated by Django 5.0.2 on 2025-12-31 02:30

from django.db import migrations, models


def print_log(apps, schema_editor):
    print("PRINTING STUFF")


def forwards_backfill_globalstat_semester_id(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE wrapped_globalstat as gstat
            SET semester_id_new = s.id
            FROM wrapped_semester s
            WHERE gstat.semester_id = s.semester;
            """
        )


def forwards_backfill_individualstat_semester_id(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE wrapped_individualstat as istat
            SET semester_id_new = s.id
            FROM wrapped_semester s
            WHERE istat.semester_id = s.semester;
            """
        )


def backwards_backfill_globalstat_semester(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE wrapped_globalstat as gstat
            SET semester_id = s.semester
            FROM wrapped_semester s
            WHERE gstat.semester_id_new = s.id;
            """
        )


def backwards_backfill_individualstat_semester(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE wrapped_individualstat as istat
            SET semester_id = s.semester
            FROM wrapped_semester s
            WHERE istat.semester_id_new = s.id;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0006_semester_current_semester_semester_unique_and_more"),
    ]

    operations = [
        # Add autogenerated unique id to Semester
        migrations.AddField(
            model_name="semester",
            name="id",
            field=models.BigIntegerField(null=True),
        ),
        # Populate id field with unique values
        migrations.RunSQL(
            sql="""
                CREATE SEQUENCE IF NOT EXISTS wrapped_semester_id_seq;
                UPDATE wrapped_semester
                SET id = nextval('wrapped_semester_id_seq')
                WHERE id IS NULL;
                ALTER SEQUENCE wrapped_semester_id_seq
                OWNED BY wrapped_semester.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(fields=["id"], name="semester_id_unique"),
        ),
        # Migrate ForeignKeys in GlobalStat to use the new Semester id field
        migrations.AddField(
            model_name="globalstat",
            name="semester_id_new",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="globalstat",
            name="semester",
            field=models.ForeignKey(
                to="wrapped.semester",
                to_field="semester",
                null=True,
                on_delete=models.CASCADE,
                related_name="+",
            ),
        ),
        migrations.RunPython(
            code=forwards_backfill_globalstat_semester_id,
            reverse_code=backwards_backfill_globalstat_semester,
        ),
        migrations.AlterField(
            model_name="globalstat",
            name="semester_id_new",
            field=models.ForeignKey(
                to="wrapped.semester",
                to_field="id",
                null=False,
                on_delete=models.CASCADE,
                related_name="+",
            ),
        ),
        migrations.RemoveField(
            model_name="globalstat",
            name="semester",
        ),
        migrations.RenameField(
            model_name="globalstat",
            old_name="semester_id_new",
            new_name="semester",
        ),
        # Migrate ForeignKeys in IndividualStat to use the new Semester id field
        migrations.AddField(
            model_name="individualstat",
            name="semester_id_new",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="individualstat",
            name="semester",
            field=models.ForeignKey(
                to="wrapped.semester",
                to_field="semester",
                null=True,
                on_delete=models.CASCADE,
                related_name="+",
            ),
        ),
        migrations.RunPython(
            code=forwards_backfill_individualstat_semester_id,
            reverse_code=backwards_backfill_individualstat_semester,
        ),
        migrations.AlterField(
            model_name="individualstat",
            name="semester_id_new",
            field=models.ForeignKey(
                to="wrapped.semester",
                to_field="id",
                null=False,
                on_delete=models.CASCADE,
                related_name="+",
            ),
        ),
        migrations.RemoveField(
            model_name="individualstat",
            name="semester",
        ),
        migrations.RenameField(
            model_name="individualstat",
            old_name="semester_id_new",
            new_name="semester",
        ),
        # Migrate ForeignKeys in SemesterPage to use the new Semester id field
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
            ADD COLUMN semester_id_new bigint;
            UPDATE wrapped_semester_pages as spage
            SET semester_id_new = s.id
            FROM wrapped_semester s
            WHERE spage.semester_id = s.semester;
            ALTER TABLE wrapped_semester_pages
            ALTER COLUMN semester_id_new SET NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
            DROP COLUMN semester_id_new;
            """,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
            ADD CONSTRAINT wrapped_semester_pages_semester_id_new_fkey
            FOREIGN KEY (semester_id_new)
            REFERENCES wrapped_semester(id)
            ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
            DROP CONSTRAINT wrapped_semester_pages_semester_id_new_fkey;
            """,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
            DROP CONSTRAINT wrapped_semester_pages_semester_id_0e2c9a76_fk;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
            ADD CONSTRAINT wrapped_semester_pages_semester_id_0e2c9a76_fk
            FOREIGN KEY (semester_id)
            REFERENCES wrapped_semester(semester)
            ON DELETE CASCADE;
            """,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
            DROP COLUMN semester_id;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
            ADD COLUMN semester_id varchar(16);
            UPDATE wrapped_semester_pages as spage
            SET semester_id = s.semester
            FROM wrapped_semester s
            WHERE spage.semester_id_new = s.id;
            ALTER TABLE wrapped_semester_pages
            ALTER COLUMN semester_id SET NOT NULL;
            """,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
            RENAME COLUMN semester_id_new TO semester_id;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
            RENAME COLUMN semester_id TO semester_id_new;
            """,
        ),
    ]
