# Generated by Django 5.0.2 on 2024-10-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0006_remove_statlocation_one_foreign_key_must_be_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='old', max_length=50),
            preserve_default=False,
        ),
    ]
