# Generated by Django 5.0.2 on 2025-12-31 02:30

from django.db import migrations, models


def print_log(apps, schema_editor):
    print("PRINTING STUFF")


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0006_semester_current_semester_semester_unique_and_more"),
    ]

    operations = [
        # Add autogenerated unique id to Semester
        migrations.AddField(
            model_name="semester",
            name="id",
            field=models.BigIntegerField(null=True),
        ),
        # Populate id field with unique values
        migrations.RunSQL(
            sql="""
                CREATE SEQUENCE IF NOT EXISTS wrapped_semester_id_seq;
                UPDATE wrapped_semester
                SET id = nextval('wrapped_semester_id_seq')
                WHERE id IS NULL;
                ALTER SEQUENCE wrapped_semester_id_seq
                OWNED BY wrapped_semester.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(fields=["id"], name="semester_id_unique"),
        ),
        # Migrate ForeignKeys in GlobalStat to use the new Semester id field
        migrations.AddField(
            model_name="globalstat",
            name="semester_id_new",
            field=models.ForeignKey(
                to="wrapped.semester",
                to_field="id",
                null=True,
                on_delete=models.CASCADE,
                related_name="+",
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE wrapped_globalstat as gstat
            SET semester_id_new_id = s.id
            FROM wrapped_semester s
            WHERE gstat.semester_id = s.semester;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="globalstat",
            name="semester_id_new",
            field=models.ForeignKey(
                to="wrapped.semester",
                to_field="id",
                null=False,
                on_delete=models.CASCADE,
                related_name="+",
            ),
        ),
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql="""
            UPDATE wrapped_globalstat as gstat
            SET semester = s.semester
            FROM wrapped_semester s
            WHERE gstat.semester_id_new_id = s.id;
            """,
        ),
        migrations.RemoveField(
            model_name="globalstat",
            name="semester",
        ),
        migrations.RenameField(
            model_name="globalstat",
            old_name="semester_id_new",
            new_name="semester",
        ),
        # Migrate ForeignKeys in IndividualStat to use the new Semester id field
        migrations.AddField(
            model_name="individualstat",
            name="semester_id_new",
            field=models.ForeignKey(
                to="wrapped.semester",
                to_field="id",
                null=True,
                on_delete=models.CASCADE,
                related_name="+",
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE wrapped_individualstat as istat
            SET semester_id_new_id = s.id
            FROM wrapped_semester s
            WHERE istat.semester_id = s.semester;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="individualstat",
            name="semester_id_new",
            field=models.ForeignKey(
                to="wrapped.semester",
                to_field="id",
                null=False,
                on_delete=models.CASCADE,
                related_name="+",
            ),
        ),
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql="""
            UPDATE wrapped_individualstat as istat
            SET semester = s.semester
            FROM wrapped_semester s
            WHERE istat.semester_id_new_id = s.id;
            """,
        ),
        migrations.RemoveField(
            model_name="individualstat",
            name="semester",
        ),
        migrations.RenameField(
            model_name="individualstat",
            old_name="semester_id_new",
            new_name="semester",
        ),
        # Migrate ForeignKeys in SemesterPage to use the new Semester id field
        migrations.RunPython(
            code=print_log,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
            ADD COLUMN semester_id_new bigint;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
            DROP COLUMN semester_id_new;
            """,
        ),
        migrations.RunSQL(
            sql="""
            UPDATE wrapped_semester_pages as spage
            SET semester_id_new = s.id
            FROM wrapped_semester s
            WHERE spage.semester_id = s.semester;
            """,
            reverse_sql="""
            UPDATE wrapped_semester_pages as spage
            SET semester_id = s.semester
            FROM wrapped_semester s
            WHERE spage.semester_id_new = s.id;
            """,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
            ALTER COLUMN semester_id SET NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
            ALTER COLUMN semester_id DROP NOT NULL;
            """,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
            ADD CONSTRAINT wrapped_semester_pages_semester_id_new_fkey
            FOREIGN KEY (semester_id_new)
            REFERENCES wrapped_semester(id)
            ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
            DROP CONSTRAINT wrapped_semester_pages_semester_id_new_fkey;
            """,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
            DROP CONSTRAINT wrapped_semester_pages_semester_id_0e2c9a76_fk;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
            ADD CONSTRAINT wrapped_semester_pages_semester_id_0e2c9a76_fk
            FOREIGN KEY (semester_id)
            REFERENCES wrapped_semester(semester)
            ON DELETE CASCADE;
            """,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
            DROP COLUMN semester_id;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
            ADD COLUMN semester_id varchar(16) NOT NULL;

            UPDATE wrapped_semester_pages as spage
            SET semester_id = s.semester
            FROM wrapped_semester s
            WHERE spage.semester_id_new = s.id;
            """,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
            RENAME COLUMN semester_id_new TO semester_id;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
            RENAME COLUMN semester_id TO semester_id_new;
            """,
        ),
        # Drop old primary key and set new primary key on id field
        migrations.RunSQL(
            sql="ALTER TABLE wrapped_semester DROP CONSTRAINT wrapped_semester_pkey;",
            reverse_sql="ALTER TABLE wrapped_semester ADD PRIMARY KEY (semester);",
        ),
        migrations.AlterField(
            model_name="semester",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="semester",
            field=models.CharField(max_length=16, unique=True, null=False, blank=False),
        ),
    ]
