# Generated by Django 5.0.2 on 2024-10-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0007_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='semester',
            field=models.CharField(default='2020A', max_length=5),
            preserve_default=False,
        ),
    ]
