# Generated by Django 5.0.2 on 2025-12-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0007_semester_pk_manual"),
    ]

    operations = [
        # Drop old primary key and set new primary key on id field
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE wrapped_semester DROP CONSTRAINT wrapped_semester_pkey;
                    ALTER TABLE wrapped_semester ADD PRIMARY KEY (id);
                    """,
                    reverse_sql="""
                    ALTER TABLE wrapped_semester DROP CONSTRAINT wrapped_semester_pkey;
                    ALTER TABLE wrapped_semester ADD PRIMARY KEY (semester);
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="semester",
                    name="semester",
                    field=models.CharField(max_length=16, primary_key=False),
                ),
                migrations.AlterField(
                    model_name="semester",
                    name="id",
                    field=models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
                DROP CONSTRAINT wrapped_semester_pages_semester_id_new_fkey;
            ALTER TABLE wrapped_globalstat
                DROP CONSTRAINT wrapped_globalstat_semester_id_d4fe9555_fk_wrapped_semester_id;
            ALTER TABLE wrapped_individualstat
                DROP CONSTRAINT wrapped_individualst_semester_id_26fd991a_fk_wrapped_s;
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester DROP CONSTRAINT wrapped_semester_pkey;
            ALTER TABLE wrapped_semester_pages
                ADD CONSTRAINT wrapped_semester_pages_semester_id_new_fkey
                FOREIGN KEY (semester_id)
                REFERENCES wrapped_semester(id);
            ALTER TABLE wrapped_globalstat
                ADD CONSTRAINT wrapped_globalstat_semester_id_d4fe9555_fk_wrapped_semester_id
                FOREIGN KEY (semester_id)
                REFERENCES wrapped_semester(id);
            ALTER TABLE wrapped_individualstat
                ADD CONSTRAINT wrapped_individualst_semester_id_26fd991a_fk_wrapped_s
                FOREIGN KEY (semester_id)
                REFERENCES wrapped_semester(id);
            ALTER TABLE wrapped_semester ADD PRIMARY KEY (id);
            """,
        ),
        migrations.RemoveConstraint(
            model_name="semester",
            name="semester_id_unique",
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE wrapped_semester_pages
                ADD CONSTRAINT wrapped_semester_pages_semester_id_new_fkey
                FOREIGN KEY (semester_id)
                REFERENCES wrapped_semester(id);
            ALTER TABLE wrapped_globalstat
                ADD CONSTRAINT wrapped_globalstat_semester_id_d4fe9555_fk_wrapped_semester_id
                FOREIGN KEY (semester_id)
                REFERENCES wrapped_semester(id);
            ALTER TABLE wrapped_individualstat
                ADD CONSTRAINT wrapped_individualst_semester_id_26fd991a_fk_wrapped_s
                FOREIGN KEY (semester_id)
                REFERENCES wrapped_semester(id);
            """,
            reverse_sql="""
            ALTER TABLE wrapped_semester_pages
                DROP CONSTRAINT wrapped_semester_pages_semester_id_new_fkey;
            ALTER TABLE wrapped_globalstat
                DROP CONSTRAINT wrapped_globalstat_semester_id_d4fe9555_fk_wrapped_semester_id;
            ALTER TABLE wrapped_individualstat
                DROP CONSTRAINT wrapped_individualst_semester_id_26fd991a_fk_wrapped_s;
            """,
        ),
        migrations.AlterField(
            model_name="globalstat",
            name="semester",
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to="wrapped.semester"),
        ),
        migrations.AlterField(
            model_name="individualstat",
            name="semester",
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to="wrapped.semester"),
        ),
    ]
