# Generated by Django 5.0.2 on 2025-12-31 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0007_semester_pk_manual"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalstat",
            name="semester",
        ),
        migrations.RenameField(
            model_name="globalstat",
            old_name="semester_id_new",
            new_name="semester",
        ),
        migrations.RemoveField(
            model_name="individualstat",
            name="semester",
        ),
        migrations.RenameField(
            model_name="individualstat",
            old_name="semester_id_new",
            new_name="semester",
        ),
    ]
