# Generated by Django 5.0.2 on 2024-11-01 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0008_page_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualStatKey',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='stat_locations',
        ),
        migrations.RenameField(
            model_name='globalstat',
            old_name='stat_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='globalstat',
            old_name='stat_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='individualstat',
            old_name='stat_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='page',
            name='id',
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='globalstat',
            unique_together={('key', 'semester')},
        ),
        migrations.CreateModel(
            name='GlobalStatThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_name', models.CharField(max_length=50)),
                ('GlobalStat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wrapped.globalstat')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='global_stats',
            field=models.ManyToManyField(blank=True, through='wrapped.GlobalStatThrough', to='wrapped.globalstat'),
        ),
        migrations.AlterUniqueTogether(
            name='individualstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='individualstat',
            name='key',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.CASCADE, to='wrapped.individualstatkey'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='individualstat',
            unique_together={('key', 'semester', 'user')},
        ),
        migrations.CreateModel(
            name='IndividualStatThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_name', models.CharField(max_length=50)),
                ('IndividualStatKey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wrapped.individualstatkey')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='individual_stats',
            field=models.ManyToManyField(blank=True, through='wrapped.IndividualStatThrough', to='wrapped.individualstatkey'),
        ),
        migrations.DeleteModel(
            name='StatLocation',
        ),
        migrations.RemoveField(
            model_name='individualstat',
            name='stat_key',
        ),
        migrations.DeleteModel(
            name='UserStatKey',
        ),
    ]
