# Generated by Django 5.0.2 on 2024-11-01 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0009_individualstatkey_remove_page_stat_locations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='globalstat',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.semester'),
        ),
        migrations.AlterField(
            model_name='individualstat',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.semester'),
        ),
        migrations.AlterField(
            model_name='page',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.semester'),
        ),
    ]
