# Generated by Django 5.0.2 on 2024-11-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0010_semester_alter_globalstat_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='semester',
        ),
        migrations.AddField(
            model_name='semester',
            name='pages',
            field=models.ManyToManyField(to='wrapped.page'),
        ),
    ]
