# Generated by Django 3.1.7 on 2021-03-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("email", models.CharField(max_length=255)),
                ("website", models.URLField(max_length=255, null=True)),
                ("facebook", models.URLField(max_length=255, null=True)),
            ],
        ),
    ]
