# Generated by Django 3.2.7 on 2022-01-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("penndata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cell", models.CharField(max_length=255)),
                ("rank", models.IntegerField()),
            ],
        ),
    ]
