# Generated by Django 4.0.3 on 2022-04-10 16:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0014_alter_post_post_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("penndata", "0002_homepageorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("cell_type", models.CharField(max_length=255)),
                ("index", models.IntegerField(default=0)),
                ("is_interaction", models.BooleanField(default=False)),
                (
                    "poll",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="portal.poll"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="portal.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        )
    ]
