# Generated by Django 4.0.1 on 2022-03-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("penndata", "0003_fitnessroom_fitnesssnapshot"),
    ]

    operations = [
        migrations.RemoveField(model_name="fitnesssnapshot", name="percent",),
    ]
