# Generated by Django 4.0.3 on 2022-04-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("penndata", "0004_analyticsevent_data"),
        ("penndata", "0005_rename_date_updated_fitnesssnapshot_date"),
    ]

    operations = []
