# Generated by Django 3.2.19 on 2023-09-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("penndata", "0006_fitnesssnapshot_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessroom",
            name="image_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
