# Generated by Django 3.1.5 on 2021-02-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dining_preferences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='laundry_preferences',
        ),
        migrations.DeleteModel(
            name='DiningVenue',
        ),
        migrations.DeleteModel(
            name='LaundryRoom',
        ),
    ]
