# Generated by Django 3.1.5 on 2021-02-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0002_auto_20210207_1231"),
        ("user", "0002_auto_20210205_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferences",
            field=models.ManyToManyField(to="laundry.LaundryRoom"),
        ),
    ]
