# Generated by Django 3.1.7 on 2021-03-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_profile_dining_preferences"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="dining_preferences",),
    ]
