# Generated by Django 3.1.7 on 2021-03-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_profile_dining_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile", name="dining_balance", field=models.FloatField(default=0),
        ),
    ]
