# Generated by Django 3.1.5 on 2021-01-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20210129_1552"),
    ]

    operations = [
        migrations.DeleteModel(name="Course",),
        migrations.AlterField(
            model_name="profile",
            name="expected_graduation",
            field=models.DateField(blank=True, null=True),
        ),
    ]
