# Generated by Django 3.1.7 on 2021-06-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20210324_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile", name="phone_number", field=models.IntegerField(null=True),
        ),
    ]
