# Generated by Django 3.1.7 on 2021-10-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsr_booking', '0003_gsr_gsrbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GSRBookingCredentials',
        ),
    ]
