# Generated by Django 3.2.7 on 2021-10-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsr_booking", "0003_gsr_gsrbooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gsr",
            name="lid",
            field=models.CharField(max_length=255),
        ),
    ]
