# Generated by Django 3.2.7 on 2021-10-24 16:31

from django.db import migrations


def create_single_user_group(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("gsr_booking", "Group")
    GroupMembership = apps.get_model("gsr_booking", "GroupMembership")
    for user in User.objects.all():
        group, created = Group.objects.get_or_create(
            owner=user,
            name="Me",
            color="#14f7d1",
        )
        if created:
            GroupMembership.objects.get_or_create(group=group, user=user, type="A", accepted=True)


class Migration(migrations.Migration):
    dependencies = [
        ("gsr_booking", "0005_reservation"),
    ]

    operations = [
        migrations.RunPython(create_single_user_group),
    ]
