# Generated by Django 3.2.7 on 2021-10-24 16:31

from django.db import migrations
from django.contrib.auth import get_user_model


def create_single_user_group(apps, schema_editor):
    User = get_user_model()
    Group = apps.get_model("gsr_booking", "Group")
    # GroupMembership = apps.get_model("gsr_booking", "GroupMembership")
    for user in User.objects.all():
        Group.objects.create(
            owner=user,
            name="my_group",
            color="",
        )
        # GroupMembership.objects.create(
        #     user=user,
        #     group=new_group,
        #     accepted=True,
        #     type="A",
        # )


class Migration(migrations.Migration):

    dependencies = [
        ("gsr_booking", "0005_reservation"),
    ]

    operations = [
        migrations.RunPython(create_single_user_group),
    ]
