# Generated by Django 3.2.7 on 2021-10-29 21:08

import django.db.models.deletion
from django.db import migrations, models


def create_reservation_for_booking(apps, schema_editor):
    """
    Creates a reservation for each booking. Only run to transition
    to using reservations. Assumes the only groups currently in database
    are single-person groups, and each user has a single-person-group
    """
    Reservation = apps.get_model("gsr_booking", "Reservation")
    GSRBooking = apps.get_model("gsr_booking", "GSRBooking")
    Group = apps.get_model("gsr_booking", "Group")

    for booking in GSRBooking.objects.all():
        single_person_group = Group.objects.filter(owner=booking.user).first()
        if single_person_group:
            reservation = Reservation.objects.create(
                start=booking.start,
                end=booking.end,
                creator=booking.user,
                group=single_person_group,
            )
            booking.reservation = reservation
            booking.save()


class Migration(migrations.Migration):
    dependencies = [
        ("gsr_booking", "0006_auto_20211024_1231"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="gsr",),
        migrations.AddField(
            model_name="gsrbooking",
            name="reservation",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="gsr_booking.reservation"
            ),
        ),
        migrations.AddField(
            model_name="reservation", name="is_cancelled", field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_reservation_for_booking),
    ]
