# Generated by Django 3.2.7 on 2021-11-07 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsr_booking", "0006_auto_20211024_1231"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GSRBookingCredentials",
        ),
    ]
