# Generated by Django 3.2.7 on 2021-11-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsr_booking', '0007_auto_20211029_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
