# Generated by Django 3.0.2 on 2020-02-02 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gsr_booking", "0007_auto_20200202_1159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gsrbookingcredentials",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
