# Generated by Django 4.0.1 on 2022-02-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsr_booking", "0008_auto_20211112_1657"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmembership",
            name="username",
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="is_wharton",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
