# Generated by Django 3.2.19 on 2023-11-12 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gsr_booking", "0010_remove_gsrbooking_reminder_sent_and_more")]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gsr_booking.group",
            ),
        )
    ]
