# Generated by Django 3.0.4 on 2020-04-19 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsr_booking", "0010_auto_20200202_1243"),
        ("gsr_booking", "0006_auto_20200207_2126"),
    ]

    operations = []
