# Generated by Django 3.2.22 on 2024-02-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsr_booking", "0011_alter_reservation_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="gsr", name="in_use", field=models.BooleanField(default=True),
        ),
    ]
