# Generated by Django 5.0.2 on 2025-10-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsr_booking", "0012_gsr_in_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="is_seas",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="gsr",
            name="kind",
            field=models.CharField(
                choices=[("WHARTON", "Wharton"), ("LIBCAL", "Libcal"), ("PENNGRP", "Penngrp")],
                default="LIBCAL",
                max_length=7,
            ),
        ),
    ]
