# Generated by Django 5.0.2 on 2025-12-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gsr_booking", "0013_groupmembership_is_seas_alter_gsr_kind"),
        ("gsr_booking", "0013_gsrsharecode"),
    ]

    operations = []
