# Generated by Django 5.0.2 on 2026-02-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gsr_booking", "0014_merge_20251207_1429"),
    ]

    operations = [
        migrations.AddField(
            model_name="gsr",
            name="bookable_days",
            field=models.IntegerField(default=7),
        ),
    ]
