# Generated by Django 3.2.23 on 2023-11-12 20:33

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[("name", models.CharField(max_length=255, primary_key=True, serialize=False)),],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sublet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("beds", models.IntegerField(blank=True, null=True)),
                ("baths", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("external_link", models.URLField(max_length=255)),
                ("min_price", models.IntegerField()),
                ("max_price", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("amenities", models.ManyToManyField(blank=True, to="sublet.Amenity")),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True, related_name="sublets_favorited", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sublettees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sublets_offered",
                        through="sublet.Offer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubletImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="sublet/images")),
                (
                    "sublet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="sublet.sublet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="offer",
            name="sublet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="sublet.sublet",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.UniqueConstraint(fields=("user", "sublet"), name="unique_offer"),
        ),
    ]
