# Generated by Django 4.2.9 on 2024-03-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sublet", "0002_auto_20240209_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sublet",
            name="baths",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
