# Generated by Django 3.2.22 on 2023-10-29 17:24

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sublet", "0002_auto_20231029_1258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
