# Generated by Django 5.0.2 on 2024-03-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sublet", "0005_sublet_is_draft_alter_sublet_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="sublet", name="is_draft",),
        migrations.AddField(
            model_name="sublet", name="is_published", field=models.BooleanField(default=False),
        ),
    ]
